apiVersion: workload.nephio.org/v1alpha1
kind: NFConfig
metadata: # kpt-merge: oai-edge/oai-upf-config
  name: oai-upf-config
  namespace: oai-edge
  annotations:
    internal.kpt.dev/upstream-identifier: 'workload.nephio.org|NFConfig|oai-edge|oai-upf-config'
spec:
  configRefs:
  - apiVersion: cellular.nephio.org/v1alpha1
    kind: PLMN
    metadata:
      name: oai-plmn
    spec:
      plmnInfo:
      - plmnID:
          mcc: "208"
          mnc: "99"
        tac: 1
        nssai:
        - sst: 1
          sd: ffffff
          dnnInfo:
          - name: internet
            sessionType: ipv4
            dns: 172.21.3.100
            subnet: 10.1.0.0/24
